apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8686
  type: LoadBalancer  # Or use NodePort, ClusterIP depending on your setup
